spring:
  application:
    name: greeting-service

  cloud:
    config:
      enabled: false
      import-check:
        enabled: false


greeting-service:
  greeting: "Oláxxx"
  default-value: "Mundo"


management:
  endpoints:
    web:
      exposure:
        include: '*'
